name: Minishell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_PAT }}
        submodules: true
    - name: Cache valgrind
      uses: actions/cache@v2
      id: cache-valgrind
      with:
        path: "~/valgrind"
        key: ${{secrets.VALGRIND_VERSION}}
    - name: Install valgrind
      env:
        CACHE_HIT: ${{steps.cache-valgrind.outputs.cache-hit}}
        VALGRIND_VERSION: ${{secrets.VALGRIND_VERSION}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp --verbose --force --recursive ~/valgrind/* /
        else
          sudo apt install --yes valgrind="$VALGRIND_VERSION"
          mkdir -p ~/valgrind
          sudo dpkg -L valgrind | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/valgrind
        fi
    - name: Run automated tests
      run: make test
