name: Minishell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone dependencies
      run: git submodule update --init
    - name: Run automated tests
      run: make libft/libft.a test
